name: "Build"
'on':
  push:
    branches:
      - master

jobs:
    build:
      strategy:
        matrix:
          include:
            - os: ubuntu-20.04
            - os: macos-10.15
        fail-fast: false

      name: "Build"
      runs-on: ${{ matrix.os }}

      steps:
        - name: "Checkout"
          uses: actions/checkout@v2

        - name: "Create build directory"
          run: |
            mkdir -p build

        - name: "Build"
          working-directory: build
          run: |
            cmake ..
            make 
            bash ../examples/run-tests.sh ../examples


    cibuildwheel:
      name: "cibuildwheel"
      runs-on: macos-10.15
      steps:
        - name: Build wheels
          uses: pypa/cibuildwheel@v2.6.1
          env:
            CIBW_BEFORE_BUILD_MACOS: |
              cd {project}
              cmake ..
              make 
              bash ../examples/run-tests.sh ../examples
            CIBW_BUILD: "cp310-macosx_x86_64"

