name: "Build"
'on':
  push:
    branches:
      - master

jobs:
    build:
      strategy:
        matrix:
          os: [ubuntu-20.04, macos-10.15]
        fail-fast: false

      name: "Build"
      runs-on: ${{ matrix.os }}

      steps:
        - name: "Checkout"
          uses: actions/checkout@v2

        - name: "Build"
          working-directory: examples
          run: |
            make


